services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sergiopeixoto3@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
    expose:
      - "${POSTGRES_PORT}"

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
      additional_contexts:
        assets: ./
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
    environment:
      NODE_ENV: ${NODE_ENV:?}
      BACKEND_API_PORT: ${BACKEND_API_PORT:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_PORT: ${POSTGRES_PORT:?}
      POSTGRES_HOST: ${POSTGRES_HOST:?}
      DB_LOGGING: ${DB_LOGGING:?}
      SESSION_SECRET: ${SESSION_SECRET:?}
      CORS_WHITELIST: ${CORS_WHITELIST:?}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.les-test.francecentral.cloudapp.azure.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=${BACKEND_API_PORT}"
    expose:
      - "${BACKEND_API_PORT}"
    command: npm run start
    deploy:
      mode: replicated
      replicas: 3

  spotlive:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/package-lock.json:/app/frontend/package-lock.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spotlive.rule=Host(`les-test.francecentral.cloudapp.azure.com`)"
      - "traefik.http.routers.spotlive.entrypoints=websecure"
      - "traefik.http.routers.spotlive.tls.certresolver=myresolver"
    expose:
      - "${VITE_APP_PORT}"
    environment:
      VITE_APP_PORT: ${VITE_APP_PORT:?}
      VITE_APP_API_URL: ${VITE_APP_API_URL:?}
    command: npm run preview
    deploy:
      mode: replicated
      replicas: 3

volumes:
  postgres-data:
  letsencrypt:
