name: Deployment Development

on:
  push:
    branches:
      - feature/deployments

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_DEV_HOST }} << 'EOF'
            cd ~/LES-T2D
            git checkout feature/deployments
            git pull
            docker-compose -f docker-compose.dev.yaml up --build -d
          EOF